sudo: required
services:
  - docker

before_install:
  - docker build -t kuangyu0801/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kuangyu0801/react-test npm test

after_success:
  - docker build -t kuangyu0801/multi-client ./client
  - docker build -t kuangyu0801/multi-nginx ./nginx
  - docker build -t kuangyu0801/multi-server ./server
  - docker build -t kuangyu0801/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push them to docker hub
  - docker push kuangyu0801/multi-client
  - docker push kuangyu0801/multi-nginx
  - docker push kuangyu0801/multi-server
  - docker push kuangyu0801/multi-worker
language: generic
