apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    # access by single node at a time
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi